# Generated by Django 4.2 on 2023-05-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImages',
        ),
        migrations.RemoveField(
            model_name='facultysignup',
            name='hod_id',
        ),
        migrations.RemoveField(
            model_name='facultysignupemail',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='hodsignup',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='hodsignupemail',
            name='hod_id',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintCategory',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='FacultySignUp',
        ),
        migrations.DeleteModel(
            name='FacultySignUpEmail',
        ),
        migrations.DeleteModel(
            name='HODSignUp',
        ),
        migrations.DeleteModel(
            name='HODSignUpEmail',
        ),
        migrations.DeleteModel(
            name='LoginActivity',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
