# Generated by Django 4.1.7 on 2023-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
