# Generated by Django 4.1.7 on 2023-05-08 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='department/images'),
            preserve_default=False,
        ),
    ]
