# Generated by Django 4.1.7 on 2023-05-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
