# Generated by Django 4.1.7 on 2023-05-13 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_complaint_is_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='withdrawn_at',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
