# Generated by Django 4.1.7 on 2023-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_complaint_withdrawn_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
