# Generated by Django 4.1.7 on 2023-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_complaint_is_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint/images'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='complaint/videos'),
        ),
    ]
