# Generated by Django 4.1.7 on 2023-05-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='resolution_status',
            field=models.BooleanField(default=False),
        ),
    ]
