# Generated by Django 4.2 on 2023-05-20 10:11

from django.db import migrations, models
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_review_resolution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make_a_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django.views.generic.base.View),
        ),
    ]
