# Generated by Django 4.2 on 2023-05-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_make_a_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Make_a_Complaint',
        ),
    ]
