# Generated by Django 4.2 on 2023-05-21 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_make_a_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cancel_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
